export const services = [
    { title: "Web Development", value: "web_development" },
    { title: "Graphic Design", value: "graphic_design" },
    { title: "Content Writing", value: "content_writing" },
    { title: "Digital Marketing", value: "digital_marketing" },
    { title: "SEO", value: "seo" },
    { title: "Video Editing", value: "video_editing" },
    { title: "Mobile App Development", value: "mobile_app_development" },
    { title: "UI/UX Design", value: "ui_ux_design" },
    { title: "Data Analysis", value: "data_analysis" },
    { title: "Virtual Assistance", value: "virtual_assistance" },
    { title: "Translation", value: "translation" },
    { title: "Voice Over", value: "voice_over" },
    { title: "Music Production", value: "music_production" },
    { title: "3D Modeling", value: "3d_modeling" },
    { title: "Animation", value: "animation" },
    { title: "Game Development", value: "game_development" },
    { title: "Cybersecurity", value: "cybersecurity" },
    { title: "IT Support", value: "it_support" },
    { title: "Cloud Computing", value: "cloud_computing" },
    { title: "Blockchain Development", value: "blockchain_development" },
    { title: "Artificial Intelligence", value: "artificial_intelligence" },
    { title: "Machine Learning", value: "machine_learning" },
    { title: "Data Science", value: "data_science" },
    { title: "Augmented Reality", value: "augmented_reality" },
    { title: "Virtual Reality", value: "virtual_reality" },
    { title: "Internet of Things", value: "internet_of_things" },
    { title: "Robotics", value: "robotics" },
    { title: "3D Printing", value: "3d_printing" },
    { title: "Wearable Technology", value: "wearable_technology" },
    { title: "Quantum Computing", value: "quantum_computing" },
]